services:
  web:
    build: .
    container_name: fdedeh-web
    restart: always
    ports:
      - "4002:3000"
    env_file:
      - path: .env
        required: true
    networks:
      - fdedeh-network
    
networks:
  fdedeh-network:
    driver: bridge
